working_dir_path: wf_mdprot_analysis
can_write_console_log: False
run_md: False

step1_cpptraj_average:
  tool: cpptraj_average
  paths:
    input_top_path: /path/to/inputs/topology.pdb
    input_traj_path: /path/to/inputs/trajectory.nc
    output_cpptraj_path: output.average.pdb
  properties:
    format: pdb

step2_cpptraj_rms_first:
  tool: cpptraj_rms
  paths:
    input_top_path: /path/to/inputs/topology.pdb
    input_traj_path: /path/to/inputs/trajectory.nc
    output_cpptraj_path: output.rmsf.dat
  properties:
    reference: first

step3_cpptraj_rms_average:
  tool: cpptraj_rms
  paths:
    input_top_path: /path/to/inputs/topology.pdb
    input_traj_path: /path/to/inputs/trajectory.nc
    output_cpptraj_path: output.rmsav.dat
  properties:
    reference: average

step4_cpptraj_bfactor:
  tool: cpptraj_bfactor
  paths:
    input_top_path: /path/to/inputs/topology.pdb
    input_traj_path: /path/to/inputs/trajectory.nc
    output_cpptraj_path: output.bfactor.dat
  properties:
    reference: first

step5_cpptraj_rgyr:
  tool: cpptraj_rgyr
  paths:
    input_top_path: /path/to/inputs/topology.pdb
    input_traj_path: /path/to/inputs/trajectory.nc
    output_cpptraj_path: output.rgyr.dat

step6_cpptraj_convert:
  tool: cpptraj_convert
  paths:
    input_top_path: /path/to/inputs/topology.pdb
    input_traj_path: /path/to/inputs/trajectory.nc
    output_cpptraj_path: output.traj.trr
  properties:
    format: trr

step7_gmx_cluster:
  tool: gmx_cluster
  paths:
    input_structure_path: /path/to/inputs/topology.pdb
    input_traj_path: dependency/step6_cpptraj_convert/output_cpptraj_path
    output_pdb_path: output.cluster.pdb
    output_cluster_log_path: output.cluster.log
  properties:
    cutoff: 0.2
