working_dir_path: wf_docking_vina
can_write_console_log: False
run_md: False

step1_fpocket_select:
  tool: fpocket_select
  paths:
    input_pockets_zip:  /path/to/inputs/all_pockets.zip
    output_pocket_pdb: fpocket_cavity.pdb
    output_pocket_pqr: fpocket_pocket.pqr
  properties:
    pocket: 8

step2_box:
  tool: box
  paths:
    input_pdb_path: dependency/step1_fpocket_select/output_pocket_pqr
    output_pdb_path: box.pdb 
  properties:
    offset: 12
    box_coordinates: True

step3_babel_convert_prep_lig:
  tool: babel_convert
  paths:
    input_path: /path/to/inputs/ligand.pdb
    output_path: prep_ligand.pdbqt
  properties:
    input_format: pdb
    output_format: pdbqt
    flex: False
    obabel_path: obabel

step4_str_check_add_hydrogens:
  tool: str_check_add_hydrogens
  paths:
    input_structure_path: /path/to/inputs/protein.pdb
    output_structure_path: prep_receptor.pdbqt
  properties:
    charges: True
    mode: auto

step5_autodock_vina_run:
  tool: autodock_vina_run
  paths:
    input_ligand_pdbqt_path: dependency/step3_babel_convert_prep_lig/output_path
    input_receptor_pdbqt_path: dependency/step4_str_check_add_hydrogens/output_structure_path
    input_box_path: dependency/step2_box/output_pdb_path
    output_pdbqt_path: output_vina.pdbqt
    output_log_path: output_vina.log

step6_babel_convert_pose_pdb:
  tool: babel_convert
  paths:
    input_path: dependency/step5_autodock_vina_run/output_pdbqt_path
    output_path: output_model.pdb
  properties:
    input_format: pdbqt
    output_format: pdb
    obabel_path: obabel
