on:
  push:
    paths:
      - common/cwl/README.md
  workflow_dispatch:

name: CWL README
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: bioexcel/biobb_workflows
          path: ./
      - name: Copy README files
        run: |
          cp common/cwl/README.md biobb_wf_amber_abc_setup/cwl/README.md
          cp common/cwl/README.md biobb_wf_amber_md_setup/cwl/README.md
          cp common/cwl/README.md biobb_wf_amber_md_setup_lig/cwl/README.md
          cp common/cwl/README.md biobb_wf_flexdyn/cwl/README.md
          sed -i '13a\> \*\*IMPORTANT!\*\* The Concoord software doesn'\''t work with dockers on Mac ARM, so in case you are using this type of computer, please comment the steps 4 to 7 as indicated in both \*\*workflow.cwl\*\* and \*\*workflow_input_descriptions.yml\*\* files.' biobb_wf_flexdyn/cwl/README.md
          sed -i '14a\\' biobb_wf_flexdyn/cwl/README.md
          cp common/cwl/README.md biobb_wf_flexserv/cwl/README.md
          cp common/cwl/README.md biobb_wf_godmd/cwl/README.md
          cp common/cwl/README.md biobb_wf_ligand_parameterization/cwl/README.md
          cp common/cwl/README.md biobb_wf_md_setup/cwl/README.md
          cp common/cwl/README.md biobb_wf_md_setup_mutations/cwl/README.mdd
          cp common/cwl/README.md biobb_wf_protein-complex_md_setup/cwl/README.md
          cp common/cwl/README.md biobb_wf_structure_checking/cwl/README.md
          cp common/cwl/README.md biobb_wf_virtual-screening_fpocket/cwl/README.md
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add */cwl/README.md && git commit -m "Updated CWL README" && git push
