name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
    paths:
      - common/docker/Dockerfile

jobs:
  build_and_publish:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          VERSION=$(grep 'LABEL version=' common/docker/Dockerfile | cut -d '"' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push biobb_wf_amber_abc_setup image
        run: |
          cd biobb_wf_amber_abc_setup/docker
          docker build --build-arg REPO=biobb_wf_amber --build-arg SUBREPO=abc_setup -t ghcr.io/bioexcel/biobb_wf_amber_abc_setup:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_amber_abc_setup:latest .
          docker push ghcr.io/bioexcel/biobb_wf_amber_abc_setup:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_amber_abc_setup:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_amber_abc_setup:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_amber_abc_setup:latest
          docker system prune -f

      - name: Build and push biobb_wf_amber_md_setup image
        run: |
          cd biobb_wf_amber_md_setup/docker
          docker build --build-arg REPO=biobb_wf_amber --build-arg SUBREPO=md_setup -t ghcr.io/bioexcel/biobb_wf_amber_md_setup:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_amber_md_setup:latest .
          docker push ghcr.io/bioexcel/biobb_wf_amber_md_setup:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_amber_md_setup:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_amber_md_setup:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_amber_md_setup:latest
          docker system prune -f

      - name: Build and push biobb_wf_amber_md_setup_lig image
        run: |
          cd biobb_wf_amber_md_setup_lig/docker
          docker build --build-arg REPO=biobb_wf_amber --build-arg SUBREPO=md_setup_lig -t ghcr.io/bioexcel/biobb_wf_amber_md_setup_lig:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_amber_md_setup_lig:latest .
          docker push ghcr.io/bioexcel/biobb_wf_amber_md_setup_lig:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_amber_md_setup_lig:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_amber_md_setup_lig:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_amber_md_setup_lig:latest
          docker system prune -f

      - name: Build and push biobb_wf_cmip image
        run: |
          cd biobb_wf_cmip/docker
          docker build --build-arg REPO=biobb_wf_cmip -t ghcr.io/bioexcel/biobb_wf_cmip:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_cmip:latest .
          docker push ghcr.io/bioexcel/biobb_wf_cmip:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_cmip:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_cmip:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_cmip:latest
          docker system prune -f

      - name: Build and push biobb_wf_dna_helparms image
        run: |
          cd biobb_wf_dna_helparms/docker
          docker build --build-arg REPO=biobb_wf_dna_helparms -t ghcr.io/bioexcel/biobb_wf_dna_helparms:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_dna_helparms:latest .
          docker push ghcr.io/bioexcel/biobb_wf_dna_helparms:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_dna_helparms:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_dna_helparms:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_dna_helparms:latest
          docker system prune -f

      - name: Build and push biobb_wf_flexdyn image
        run: |
          cd biobb_wf_flexdyn/docker
          docker build --build-arg REPO=biobb_wf_flexdyn -t ghcr.io/bioexcel/biobb_wf_flexdyn:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_flexdyn:latest .
          docker push ghcr.io/bioexcel/biobb_wf_flexdyn:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_flexdyn:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_flexdyn:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_flexdyn:latest
          docker system prune -f

      - name: Build and push biobb_wf_flexserv image
        run: |
          cd biobb_wf_flexserv/docker
          docker build --build-arg REPO=biobb_wf_flexserv -t ghcr.io/bioexcel/biobb_wf_flexserv:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_flexserv:latest .
          docker push ghcr.io/bioexcel/biobb_wf_flexserv:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_flexserv:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_flexserv:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_flexserv:latest
          docker system prune -f

      - name: Build and push biobb_wf_godmd image
        run: |
          cd biobb_wf_godmd/docker
          docker build --build-arg REPO=biobb_wf_godmd -t ghcr.io/bioexcel/biobb_wf_godmd:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_godmd:latest .
          docker push ghcr.io/bioexcel/biobb_wf_godmd:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_godmd:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_godmd:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_godmd:latest
          docker system prune -f

      - name: Build and push biobb_wf_ligand_parameterization image
        run: |
          cd biobb_wf_ligand_parameterization/docker
          docker build --build-arg REPO=biobb_wf_ligand_parameterization -t ghcr.io/bioexcel/biobb_wf_ligand_parameterization:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_ligand_parameterization:latest .
          docker push ghcr.io/bioexcel/biobb_wf_ligand_parameterization:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_ligand_parameterization:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_ligand_parameterization:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_ligand_parameterization:latest
          docker system prune -f

      - name: Build and push biobb_wf_md_setup image
        run: |
          cd biobb_wf_md_setup/docker
          docker build --build-arg REPO=biobb_wf_md_setup -t ghcr.io/bioexcel/biobb_wf_md_setup:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_md_setup:latest .
          docker push ghcr.io/bioexcel/biobb_wf_md_setup:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_md_setup:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_md_setup:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_md_setup:latest
          docker system prune -f

      - name: Build and push biobb_wf_md_setup_mutations image
        run: |
          cd biobb_wf_md_setup_mutations/docker
          docker build --build-arg REPO=biobb_wf_md_setup_mutations -t ghcr.io/bioexcel/biobb_wf_md_setup_mutations:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_md_setup_mutations:latest .
          docker push ghcr.io/bioexcel/biobb_wf_md_setup_mutations:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_md_setup_mutations:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_md_setup_mutations:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_md_setup_mutations:latest
          docker system prune -f

      - name: Build and push biobb_wf_pmx_tutorial image
        run: |
          cd biobb_wf_pmx_tutorial/docker
          docker build --build-arg REPO=biobb_wf_pmx_tutorial -t ghcr.io/bioexcel/biobb_wf_pmx_tutorial:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_pmx_tutorial:latest .
          docker push ghcr.io/bioexcel/biobb_wf_pmx_tutorial:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_pmx_tutorial:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_pmx_tutorial:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_pmx_tutorial:latest
          docker system prune -f

      - name: Build and push biobb_wf_protein_md_analysis image
        run: |
          cd biobb_wf_protein_md_analysis/docker
          docker build --build-arg REPO=biobb_wf_protein_md_analysis -t ghcr.io/bioexcel/biobb_wf_protein_md_analysis:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_protein_md_analysis:latest .
          docker push ghcr.io/bioexcel/biobb_wf_protein_md_analysis:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_protein_md_analysis:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_protein_md_analysis:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_protein_md_analysis:latest
          docker system prune -f

      - name: Build and push biobb_wf_protein-complex_md_setup image
        run: |
          cd biobb_wf_protein-complex_md_setup/docker
          docker build --build-arg REPO=biobb_wf_protein-complex_md_setup -t ghcr.io/bioexcel/biobb_wf_protein-complex_md_setup:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_protein-complex_md_setup:latest .
          docker push ghcr.io/bioexcel/biobb_wf_protein-complex_md_setup:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_protein-complex_md_setup:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_protein-complex_md_setup:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_protein-complex_md_setup:latest
          docker system prune -f

      - name: Build and push biobb_wf_structure_checking image
        run: |
          cd biobb_wf_structure_checking/docker
          docker build --build-arg REPO=biobb_wf_structure_checking -t ghcr.io/bioexcel/biobb_wf_structure_checking:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_structure_checking:latest .
          docker push ghcr.io/bioexcel/biobb_wf_structure_checking:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_structure_checking:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_structure_checking:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_structure_checking:latest
          docker system prune -f

      - name: Build and push biobb_wf_virtual-screening_fpocket image
        run: |
          cd biobb_wf_virtual-screening_fpocket/docker
          docker build --build-arg REPO=biobb_wf_virtual-screening --build-arg SUBREPO=fpocket -t ghcr.io/bioexcel/biobb_wf_virtual-screening_fpocket:${{ env.VERSION }} -t ghcr.io/bioexcel/biobb_wf_virtual-screening_fpocket:latest .
          docker push ghcr.io/bioexcel/biobb_wf_virtual-screening_fpocket:${{ env.VERSION }}
          docker push ghcr.io/bioexcel/biobb_wf_virtual-screening_fpocket:latest
          docker rmi ghcr.io/bioexcel/biobb_wf_virtual-screening_fpocket:${{ env.VERSION }}
          docker rmi ghcr.io/bioexcel/biobb_wf_virtual-screening_fpocket:latest
          docker system prune -f


