name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
    paths:
      - common/docker/Dockerfile

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push biobb_wf_amber_abc_setup image
        run: |
          cd biobb_wf_amber_abc_setup/docker
          docker build --build-arg REPO=biobb_wf_amber --build-arg SUBREPO=abc_setup -t ghcr.io/bioexcel/biobb_wf_amber_abc_setup:latest .
          docker push ghcr.io/bioexcel/biobb_wf_amber_abc_setup:latest

      - name: Make biobb_wf_amber_abc_setup image public
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            https://api.github.com/orgs/bioexcel/packages/container/biobb_wf_amber_abc_setup/visibility \
            -d '{"visibility":"public"}'
