name: Python workflow Tests

on:
  push:
    paths:
      - biobb_wf_ligand_parameterization/python/workflow.env.yml
  workflow_dispatch:

jobs:
  biobb_wf_ligand_parameterization:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'biobb_wf_ligand_parameterization/python/workflow.env.yml')
    #needs: files
    #if: contains(needs.files.outputs.changed_files, 'biobb_wf_ligand_parameterization/python/workflow.env.yml')
    uses: ./.github/workflows/common-python.yaml
    with:
      wf_name: biobb_wf_ligand_parameterization

