on:
  push:
    paths:
      - common/python/README_common.md
      - common/python/README_subrepo.md
  workflow_dispatch:

name: Python README
jobs:
  python_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-murray/workflow-application-token-action@v3
        id: generate_token
        with:
          application_id: ${{ vars.GHAPUSH }}
          application_private_key: ${{ secrets.GHAPUSH }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Copy README files
        run: |
          cp common/python/README_subrepo.md biobb_wf_amber_abc_setup/python/README.md
          cp common/python/README_subrepo.md biobb_wf_amber_md_setup/python/README.md
          cp common/python/README_subrepo.md biobb_wf_amber_md_setup_lig/python/README.md
          cp common/python/README_common.md biobb_wf_cmip/python/README.md
          cp common/python/README_common.md biobb_wf_dna_helparms/python/README.md
          cp common/python/README_common.md biobb_wf_flexdyn/python/README.md
          cp common/python/README_common.md biobb_wf_flexserv/python/README.md
          cp common/python/README_common.md biobb_wf_godmd/python/README.md
          cp common/python/README_common.md biobb_wf_ligand_parameterization/python/README.md
          cp common/python/README_common.md biobb_wf_md_setup/python/README.md
          cp common/python/README_common.md biobb_wf_md_setup_mutations/python/README.md
          cp common/python/README_common.md biobb_wf_pmx_tutorial/python/README.md
          cp common/python/README_common.md biobb_wf_protein_md_analysis/python/README.md
          cp common/python/README_common.md biobb_wf_protein-complex_md_setup/python/README.md
          cp common/python/README_common.md biobb_wf_structure_checking/python/README.md
          cp common/python/README_subrepo.md biobb_wf_virtual-screening_fpocket/python/README.md
      - name: Replace placeholders in README
        run: |
          sed -i "s/<repository>/biobb_wf_amber/g" biobb_wf_amber_abc_setup/python/README.md
          sed -i "s/<subrepository>/abc_setup/g" biobb_wf_amber_abc_setup/python/README.md
          sed -i "s/<repository>/biobb_wf_amber/g" biobb_wf_amber_md_setup/python/README.md
          sed -i "s/<subrepository>/md_setup/g" biobb_wf_amber_md_setup/python/README.md
          sed -i "s/<repository>/biobb_wf_amber/g" biobb_wf_amber_md_setup_lig/python/README.md
          sed -i "s/<subrepository>/md_setup_lig/g" biobb_wf_amber_md_setup_lig/python/README.md
          sed -i "s/<repository>/biobb_wf_cmip/g" biobb_wf_cmip/python/README.md
          sed -i "s/<repository>/biobb_wf_dna_helparms/g" biobb_wf_dna_helparms/python/README.md
          sed -i "s/<repository>/biobb_wf_flexdyn/g" biobb_wf_flexdyn/python/README.md
          sed -i "s/<repository>/biobb_wf_flexserv/g" biobb_wf_flexserv/python/README.md
          sed -i "s/<repository>/biobb_wf_godmd/g" biobb_wf_godmd/python/README.md
          sed -i "s/<repository>/biobb_wf_ligand_parameterization/g" biobb_wf_ligand_parameterization/python/README.md
          sed -i "s/<repository>/biobb_wf_md_setup/g" biobb_wf_md_setup/python/README.md
          sed -i "s/<repository>/biobb_wf_md_setup_mutations/g" biobb_wf_md_setup_mutations/python/README.md
          sed -i "s/<repository>/biobb_wf_pmx_tutorial/g" biobb_wf_pmx_tutorial/python/README.md
          sed -i "s/<repository>/biobb_wf_protein_md_analysis/g" biobb_wf_protein_md_analysis/python/README.md
          sed -i "s/<repository>/biobb_wf_protein-complex_md_setup/g" biobb_wf_protein-complex_md_setup/python/README.md
          sed -i "s/<repository>/biobb_wf_structure_checking/g" biobb_wf_structure_checking/python/README.md
          sed -i "s/<repository>/biobb_wf_virtual-screening/g" biobb_wf_virtual-screening_fpocket/python/README.md
          sed -i "s/<subrepository>/fpocket/g" biobb_wf_virtual-screening_fpocket/python/README.md
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add */python/README.md && git commit -m "Updated python README" && git push
