name: Common Python

on:
  workflow_call:
    inputs:
      wf_name:
        required: true
        type: string
      runs_on:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  python:
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: 2880
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "Repository -> ${{ github.repository }}"
      - run: echo "Branch -> ${{ github.ref }}"
      - run: echo "Trigger event -> ${{ github.event_name }}"
      - run: echo "Runner OS -> ${{ runner.os }}"

      - name: List files in the repository
        run: |
          ls -R ${{ github.workspace }}

      - name: Remove all micromamba installations
        run: |
          rm -rf $HOME/.bash_profile $HOME/.conda $HOME/micromamba $HOME/micromamba-bin 2>/dev/null
          touch $HOME/.bash_profile

      - name: setup-micromamba
        uses: mamba-org/setup-micromamba@v2.0.0
        with:
          generate-run-shell: true
          micromamba-version: '2.0.2-2'
          post-cleanup: 'all'
          init-shell: bash
          environment-file: ${{ inputs.wf_name }}/python/workflow.env.yml
          create-args: >-
            pytest
            imagehash

      - name: List installed package versions
        shell: bash -l {0}
        run: micromamba list

      - name: Run tests
        shell: bash -l {0}
        run: |
          export PYTHONPATH=.:./biobb_common:$PYTHONPATH

          cd ${{ inputs.wf_name }}/tests/python

          # Production one
          pytest -s ${{ inputs.wf_name }}.py --config ../../python/workflow.yml --remove
