name: Python workflow Tests

on:
  push:
    paths:
      - biobb_wf_ligand_parameterization/python/workflow.env.yml
      - biobb_wf_ligand_parameterization/python/workflow.py
      #- biobb_wf_md_setup/python/workflow.env.yml
      #- biobb_wf_md_setup/python/workflow.py
  workflow_dispatch:

jobs:
  filter-files:
    name: Filter Files
    runs-on: self-hosted
    outputs:
      biobb_wf_ligand_parameterization_changed: ${{ steps.filter.outputs.biobb_wf_ligand_parameterization }}
      biobb_wf_md_setup_changed: ${{ steps.filter.outputs.biobb_wf_md_setup }}
    steps:
      - name: Filter Changed Files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            biobb_wf_ligand_parameterization:
              - "biobb_wf_ligand_parameterization/python/workflow.env.yml"
              - "biobb_wf_ligand_parameterization/python/workflow.py"
            biobb_wf_md_setup:
              - "biobb_wf_md_setup/python/workflow.env.yml"
              - "biobb_wf_md_setup/python/workflow.py"

  biobb_wf_ligand_parameterization:
    name: biobb_wf_ligand_parameterization
    needs: filter-files
    uses: ./.github/workflows/python-reusable.yaml
    if: needs.filter-files.outputs.biobb_wf_ligand_parameterization_changed == 'true'
    with:
      wf_name: biobb_wf_ligand_parameterization

  # biobb_wf_md_setup:
  #   name: biobb_wf_md_setup
  #   needs: filter-files
  #   uses: ./.github/workflows/python-reusable.yaml
  #   if: needs.filter-files.outputs.biobb_wf_md_setup_changed == 'true'
  #   with:
  #     wf_name: biobb_wf_md_setup
